apiVersion: v1
kind: Service
metadata:
  name: forex-service
  labels:
    app: forex-service
spec:
  ports:
    - port: 8098
      name: http
  selector:
    app: forex-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: forex-service-v1
  labels:
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: forex-service
        version: v1
    spec:
      containers:
        - name: forex-service
          image: anastayaa/forex-image
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: IfNotPresent #Always
          ports:
            - containerPort: 8098